services:
  # Backend API Service
  - type: web
    name: task-management-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        fromDatabase:
          name: task-management-db
          property: connectionString

  # Frontend Service
  - type: web
    name: task-management-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://task-management-api.onrender.com

databases:
  - name: task-management-db
    databaseName: taskmanagement
    plan: free
